### PR TITLE
feat: Adapt to 8.x: Remove _type field

### PR DESCRIPTION
**Pull request by Yunfly**
https://www.elastic.co/guide/en/elasticsearch/reference/8.0/docs-bulk.html  doesn't support _type  

send request:
`{"index":{"_index":"openapi","_type":"application"}}
{"message":"\n*************** info log start ***************\ninfo detail: \n {\n  \"gid\": \"gid\",\n  \"content\": \"contentParse\",\n  \"appid\": \"body.appid\",\n  \"nonce_str\": \"body.nonce_str\",\n  \"path\": \"/api/v1/open/test\"\n} \n\n*************** info log end ***************\n","context":{},"level":200,"level_name":"INFO","channel":"test-channel","datetime":"2024-01-31T10:20:48.481Z","extra":{}}`

get 400 error response:

`log4js.logstashHTTP Appender error posting to http://elastic:Dwxg6t2ZQJuWaB@10.8.251.31:9200/_bulk: 400 - {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}`

### CODE REVIEW

**Comment by lamweili** [comment]
A major semver upgrade would be needed, am I right?

**Comment by Yunfly** [comment]
> A major semver upgrade would be needed, am I right?

yes

**Comment by Yunfly** [comment]
is there anything that needs adjustment in my Commits? I need to rely on this repository to upload logs to Elasticsearch 8.0.

**Comment by Yunfly** [comment]
ignore params logType can fix

**Pull request closed without merging**
